name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/copilot-setup-steps.yml
    strategy:
      matrix:
        java: [ '17', '21' ]
    with:
      java-version: ${{ matrix.java }}
      run: './mvnw -B -ntp clean test'
    secrets: inherit
