name: "Copilot Setup Steps"

on:
  # Allow Copilot to detect and run this job before a session; also allow easy validation
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  # Keep reusable mode so other workflows can call these steps with inputs, if desired
  workflow_call:
    inputs:
      java-version:
        description: Java version to install (SemVer or major)
        type: string
        default: '17'
      run:
        description: Optional shell command to run after setup (e.g., './mvnw -B -ntp clean test')
        type: string
        default: ''

jobs:
  # The job MUST be named exactly 'copilot-setup-steps' for Copilot coding agent to pick it up.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Java (Temurin) with Maven cache
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          # Use input when called as a reusable workflow; default to 17 for Copilot session runs
          java-version: ${{ inputs.java-version || '17' }}
          cache: maven

      - name: Ensure Maven Wrapper is executable
        run: |
          if [ -f ./mvnw ]; then chmod +x ./mvnw; fi

      - name: Print tool versions
        run: |
          ./mvnw -v || true
          java -version || true
          echo "Runner: $RUNNER_OS / $(uname -a)"

      - name: Pre-warm Maven local repository (dependencies & plugins)
        shell: bash
        run: |
          if [ -f ./mvnw ]; then
            ./mvnw -B -ntp -q -DskipTests dependency:go-offline || true
          fi

      - name: Optional custom command from caller
        # Only attempt to use inputs.run when this workflow is invoked via workflow_call
        if: ${{ github.event_name == 'workflow_call' && inputs.run != '' }}
        run: ${{ inputs.run }}
